#!/bin/sh /etc/rc.common
 
START=99
STOP=99
  
start() {
    echo 7 > /sys/class/gpio/export 
    echo out > /sys/class/gpio/gpio7/direction
}                 
                   
stop() {
    echo > /dev/null
}

